#!/bin/bash

DIR="/home/iaquobe/git/updated-website.git"

TARGET="/home/iaquobe/updated-website"
while read oldrev newrev ref
do
	BRANCH=$(git rev-parse --symbolic --abbrev-ref $ref)
	if [[ $BRANCH == "main" ]]; then
		echo "Push received! Deploying branch: ${BRANCH}..."
		# deploy to our target directory.
		git --work-tree="$TARGET" checkout -f $BRANCH
		cd $TARGET
		exec ./update-website.sh
	else
		echo "$BRANCH Not master branch. Skipping."
	fi
done
